# Site settings
title: "My Data Analysis Project"
description: "A website showcasing my project on data analysis and methodology."
baseurl: "" # Leave this blank unless you are deploying the site in a subfolder (e.g., /project)
url: "https://<your-username>.github.io/<repository-name>" # Your live site URL
author: Xizhen Cai

# Theme settings
theme: jekyll-theme-cayman # Choose a theme (e.g., minima, jekyll-theme-cayman, jekyll-theme-slate, etc.)
plugins:
  - jekyll-feed # Optional: Provides an RSS feed

# Navigation links (optional)
nav_links:
  - title: "Home"
    url: "/index"
  - title: "Data Description"
    url: "/data-description"
  - title: "Methodology"
    url: "/methodology"
  - title: "Results"
    url: "/docs/results"
  - title: "Conclusions"
    url: "/conclusions"

# Markdown settings
markdown: kramdown # GitHub Pages uses Kramdown by default for Markdown processing
highlighter: rouge # For syntax highlighting in code blocks

# SEO and social (optional)
social:
  github_username: yourusername # Display a GitHub link in footer
  twitter_username: yourtwitterhandle # Optional: If you want to add social links
