# Site settings
title: "My Data Analysis Project"
description: "A website showcasing my data analysis project."
url: "https://xizhen-cai.github.io/sample_project/"  # Replace with your GitHub Pages URL
author: Xizhen Cai  # Your name

# Theme settings
theme: minima # You can replace this with other supported GitHub Pages themes like jekyll-theme-cayman, slate, etc.

# Optional plugins
plugins:
  - jekyll-feed  # This plugin adds an RSS feed to your site
  - jekyll-seo-tag  # Adds SEO optimization tags to your site
  - jekyll-sitemap  # Automatically generates a sitemap

# Navigation links (optional, if your theme supports them)
nav_links:
  - title: "Home"
    url: "/"
  - title: "1. Data Description"
    url: "/data"
  - title: "2. Methodology"
    url: "/methodology"
  - title: "3. Results"
    url: "/results"
  - title: "4. Conclusions"
    URL: "/conclusion"

# Markdown settings
markdown: kramdown  # Default for GitHub Pages
highlighter: rouge  # Syntax highlighting for code blocks

# Build settings (optional)
future: true  # Show future-dated posts
